#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPT="$DIR/cvm-start-agent.sh"
OUT="$DIR/docker-compose.phala.agent.yml"
python3 - "$SCRIPT" "$OUT" <<'PY'
import sys
from pathlib import Path

script = Path(sys.argv[1]).read_text().replace("$", "$$")
out = Path(sys.argv[2])
header = """# Generated by prepare-compose-agent.sh — deploy with:
#   phala deploy -c docker-compose.phala.agent.yml -n skillvault-agent -t tdx.xlarge --wait \\
#     -e NEAR_API_KEY="$NEAR_API_KEY"
services:
  skillvault-agent:
    image: python:3.12-slim
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - sandbox_data:/tmp/skillvault-sandbox
    configs:
      - source: cvm_start_agent
        target: /usr/local/bin/cvm-start-agent.sh
        mode: "0555"
    entrypoint: ["/usr/local/bin/cvm-start-agent.sh"]
    environment:
      RUNNER_MODE: dstack
      DSTACK_STRICT: "true"
      MODEL_MODE: near_private
      INFERENCE_PROVIDER: near_private
      MODEL_SERVER_URL: http://127.0.0.1:8000
      NEAR_API_KEY: ${NEAR_API_KEY}
      NEAR_COMPLETIONS_BASE: ${NEAR_COMPLETIONS_BASE:-https://qwen3-30b.completions.near.ai/v1}
      NEAR_MODEL_SLUG: ${NEAR_MODEL_SLUG:-qwen3-30b}
      USE_SANDBOX_FOR_AGENT: "false"
      MODEL_PROXY_URL: http://127.0.0.1:8080
      RUNNER_HASH: ${RUNNER_HASH:-sha256:skillvault-tee-runner-v2}
      VERIFIER_HASH: ${VERIFIER_HASH:-sha256:skillvault-verifier-v2}
      MODEL_HASH: ${MODEL_HASH:-sha256:near-qwen3-30b}
      SKILLVAULT_REPO: https://github.com/gokulnpc/skill-marketplace-tee.git
      SKILLVAULT_REF: main

configs:
  cvm_start_agent:
    content: |
"""
footer = """
volumes:
  sandbox_data:
"""
indented = "".join(f"      {line}" if line.strip() else "\n" for line in script.splitlines(keepends=True))
out.write_text(header + indented + footer)
print(f"Wrote {out}")
PY
