#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPT="$DIR/cvm-start.sh"
OUT="$DIR/docker-compose.phala.yml"
python3 - "$SCRIPT" "$OUT" <<'PY'
import sys
from pathlib import Path

script = Path(sys.argv[1]).read_text().replace("$", "$$")
out = Path(sys.argv[2])
header = """# Generated by prepare-compose.sh — deploy with:
#   phala deploy -c docker-compose.phala.yml -n skillvault-tee -t tdx.xlarge --wait
services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama

  skillvault-tee:
    image: python:3.12-slim
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    configs:
      - source: cvm_start
        target: /usr/local/bin/cvm-start.sh
        mode: "0555"
    entrypoint: ["/usr/local/bin/cvm-start.sh"]
    environment:
      RUNNER_MODE: dstack
      DSTACK_STRICT: "true"
      MODEL_MODE: ollama
      MODEL_NAME: llama3.1:8b
      MODEL_HASH: sha256:ollama-llama3.1-8b
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_PULL_ON_START: "true"
      MODEL_SERVER_URL: http://127.0.0.1:8000
      RUNNER_HASH: ${RUNNER_HASH:-sha256:skillvault-tee-runner-v1}
      VERIFIER_HASH: ${VERIFIER_HASH:-sha256:skillvault-verifier-v1}
      SKILLVAULT_REPO: https://github.com/gokulnpc/skill-marketplace-tee.git
      SKILLVAULT_REF: main
    depends_on:
      - ollama

configs:
  cvm_start:
    content: |
"""
footer = """
volumes:
  ollama_data:
"""
indented = "".join(f"      {line}" if line.strip() else "\n" for line in script.splitlines(keepends=True))
out.write_text(header + indented + footer)
print(f"Wrote {out}")
PY
